# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

# .rubocop.yml
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - 'db/schema.rb'

Layout/TrailingEmptyLines:
  Enabled: true

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
